backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Video", name: "video", widget: "string", required: false }
      - { label: "Technologies", name: "technologies", widget: "list", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", required: false }
      - { label: "Visible", name: "visible", widget: "boolean", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Project URL", name: "projectUrl", widget: "string", required: false }
      - { label: "GitHub URL", name: "githubUrl", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string", required: false }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", required: false }
      - { label: "Visible", name: "visible", widget: "boolean", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Body", name: "body", widget: "markdown" }